<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly!
}

if ( ! interface_exists( 'WPSC_PS_AIT_Provider_Interface' ) ) :

	interface WPSC_PS_AIT_Provider_Interface {

		/**
		 * Get the store ID for a given provider.
		 *
		 * @param string $api_key The name of the provider.
		 * @return string The store ID associated with the provider.
		 */
		public function wpsc_provider_store_id( $api_key );

		/**
		 * Clear this provider's cached vector/file-search store ID so the next call to
		 * wpsc_provider_store_id() creates a fresh one under whichever key/project is
		 * currently configured. Needed because these stores are project-scoped and never
		 * re-validated on their own once cached (e.g. after an API key rotation).
		 *
		 * @return void
		 */
		public function wpsc_clear_provider_store_id();

		/**
		 * Extract AI metadata from a prompt.
		 *
		 * @param array  $ai_settings The AI settings array.
		 * @param string $system_prompt The system prompt used for AI training.
		 * @param string $user_prompt The user prompt containing the draft reply and context for the AI.
		 * @return array The extracted metadata.
		 */
		public function wpsc_get_file_meta_data( $ai_settings, $system_prompt, $user_prompt );

		/**
		 * Attach a file to the vector store.
		 *
		 * @param string $vector_store_id ID of the vector store.
		 * @param string $file_id ID of the file to attach.
		 * @param string $api_key API key for authentication.
		 */
		public function wpsc_attach_file( $vector_store_id, $file_id, $api_key );

		/**
		 * Upload a file to the provider.
		 *
		 * @param string $file_path Path to the file.
		 * @param string $api_key API key for authentication.
		 * @return mixed The response from the provider.
		 */
		public function wpsc_upload_file( $file_path, $api_key );

		/**
		 * Generate a polished reply using the AI provider.
		 *
		 * @param array  $ai_settings AI settings array.
		 * @param string $system_prompt The system prompt used for AI training.
		 * @param string $prompt The user prompt containing the draft reply and context for the AI.
		 * @param int    $ticket_id The ID of the ticket being processed.
		 * @return string The polished reply generated by the AI provider.
		 */
		public function wpsc_generate_polished_reply( $ai_settings, $system_prompt, $prompt, $ticket_id );

		/**
		 * Get the content of a file.
		 *
		 * @param string $draft_content The prompt containing the draft reply and context for the AI.
		 * @param int    $ticket_id The ID of the ticket being processed.
		 * @return string The content of the file.
		 */
		public function wpsc_improve_draft_content( $draft_content, $ticket_id );

		/**
		 * Generate an auto draft reply for a customer's reply.
		 *
		 * @param array       $ai_settings AI settings array.
		 * @param WPSC_Ticket $ticket The ticket model instance.
		 * @return array|false The AI draft response or false on error.
		 */
		public function wpsc_auto_draft_ticket_reply( $ai_settings, $ticket );

		/**
		 * Clean the content of a row for RAG (Retrieval-Augmented Generation) processing.
		 *
		 * @param string $system_prompt The system prompt used for AI training.
		 * @param array  $ai_settings The AI settings array.
		 * @return string The cleaned content ready for RAG processing.
		 */
		public function wpsc_clean_row_content_for_rag( $system_prompt, $ai_settings );

		/**
		 * Delete a training record from Gemini.
		 *
		 * @param string $file The file to be deleted.
		 * @param array  $ai_settings The AI settings associated with the training record.
		 * @return mixed The response from the provider after attempting to delete the training record.
		 */
		public function wpsc_delete_training_record( $file, $ai_settings );
	}
endif;
